### ISSUE TITLE
various errors and suggestions

### ISSUE THREAD

**Issue by 2bithack** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift3-V2#1]
hoppy bunny
various suggestions, things in parenthesis are either missing words or extra letters.
if you have trouble locating where the issues are please let me know.

-Adding Controls:
third info blue box mentions
 “winter academy” 

-Scrolling the World: 
Scrolling Sprites, “if the x position is less than negative have(half) the width” “This means when a sprite’s x position is negative have(half)..”
“To create an endless scrolling ground plane you will (use) two sections.

"Open GameScene.swift add the following at the top of the GameScene class under let scrollSpeed." (haven’t defined scrollSpeed yet)

**There are two different methods for scrolling the ground. the old one with the scrollLayer node scrollWorld(). and a new one for scrolling sprites specifically: scrollSprite(). if you use both there is an error because the ground is set as a child to the scroll layer and you set a reference for groundA and groundB as children of the scene

-Adding Obstacles
“sometimes you need to have a(to) play in the visual editor and then adjust”

Dynamic obstacle generation
“you added an(in) a copy (of) Obstacle.sks

Add (a) variable at the top of(under) your (GameScene) class

Obstacle Layer
“It will (be) useful..”

Obstacle Scrolling

**obstacles is removed from scene too early. the value for the condition to check if the obstacle has left the scene removes the object when the anchor which is half the obstacle sprite width hits 0, then it removes the obstacle sprite, which isn’t exactly when it’s left the screen. changed the 0 to -26

-Setting up collision
Shutting down the world
“it’s not perfect yet as the bunny will still respond ever(y) so slightly to touch and the world will continue to scroll by

**there was no initial start button for the game.

**Comment by dionlarson** [comment]
Finished fixing in 309f3d0
