### ISSUE TITLE
6. Scrolling the world

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift3-V2#6]
In 'Creating endless ground':

"Open GameScene.swift add the following at the top of the GameScene class under let scrollSpeed."

At this point, we have not yet defined a scrollSpeed.

**Comment by zontan** [comment]
Actually, let's just append that this whole page is messed up. The 'creating endless ground' section appears to be totally removed from the rest of the page. It gives us a generic scroll function that can scroll any sprite and jump things back when they fall off the screen... and then the next two sections totally ignore that the previous section exists.

In addition, the two sections offer completely different ways of scrolling - one uses a scrollLayer, the other doesn't. One just uses '5' and the other wants to use 100 * delta. It looks like the new 'creating endless ground' section was added with no regard to what was already there.

**Comment by dionlarson** [comment]
Yeah, the page was rewritten but somehow retained the previous content in a bad merge. Fixing in a moment...

**Comment by dionlarson** [comment]
Removed section on `scrollSprite` to make it consistent with `scrollObstacles`.
