### ISSUE TITLE
8. Setting up collisions

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift3-V2#7]
<img width="641" alt="screen shot 2017-06-06 at 10 24 57 pm" src="https://user-images.githubusercontent.com/13054451/26859612-ff1f03b2-4b06-11e7-8a53-419e756538bf.png">

Should this be the most current Xcode version? If so: Version 8.3.3

**Comment by dionlarson** [comment]
Fixed / removed.
